#!/usr/bin/perl

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::Build::CreateLinks qw(:all);

#
# nethserver-vsftpd-update event
#
my $event = 'nethserver-vsftpd-update';

event_actions($event, qw(
      initialize-default-databases 00
));

event_templates($event, qw(
      /etc/vsftpd/vsftpd.conf
      /etc/vsftpd/chroot_list  
      /etc/vsftpd/user_list
));

event_services($event, 'vsftpd' => 'restart');


#
# nethserver-vsftpd-update event
#
$event = 'nethserver-vsftpd-save';

event_actions($event, qw(
      nethserver-vsftpd-users 20
      nethserver-vsftpd-modprobe 30
      firewall-adjust 40
));

event_templates($event, qw(
      /etc/vsftpd/vsftpd.conf
      /etc/vsftpd/chroot_list  
      /etc/vsftpd/user_list
));

event_services($event, 'vsftpd' => 'restart');
