#!/usr/bin/php
<?php
/*
 * Copyright (C) 2019 Nethesis S.r.l.
 * http://www.nethesis.it - nethserver@nethesis.it
 *
 * This script is part of NethServer.
 *
 * NethServer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License,
 * or any later version.
 *
 * NethServer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with NethServer.  If not, see COPYING.
*/
require_once("/usr/libexec/nethserver/api/lib/Helpers.php");
$data = readInput();
$adb = new EsmithDatabase('accounts');
$v = new LegacyValidator($data['ftp']);


// check if key exists
if($data['action'] == 'create') {
    if($adb->getKey($data['ftp']['name'])) {
        $v->addValidationError('name', "key_already_exists");
    }
}

$v->declareParameter('name', Validate::USERNAME);
$v->declareParameter('Password', Validate::ANYTHING);
$v->declareParameter('Chroot', Validate::SERVICESTATUS);
$v->declareParameter('ChrootDir', Validate::ANYTHING);
$v->declareParameter('status', Validate::SERVICESTATUS);
$v->declareParameter('Description',Validate::ANYTHING);

# Validate the input
if ($v->validate()) {
    success();
} else {
    error($v);
}
