#!/usr/bin/perl

use esmith::AccountsDB;
use esmith::ConfigDB;
use File::Temp qw(tempfile);
use File::Path qw(mkpath);

my $cdb = esmith::ConfigDB->open_ro or die "Couldn't open ConfigDB\n";
my $adb = esmith::AccountsDB->open_ro or die "Couldn't open AccountsDB\n";
my $uid = getpwnam "ftp";
my $gid = getgrnam "ftp";

my $vsftpd = $cdb->get('vsftpd');
my $usertype = $vsftpd->prop('UserType') || 'virtual';

# Clean up specific configuration per user
unlink glob "/etc/vsftpd/users/*";

my $tmp;
if ($usertype eq 'virtual') {
    $tmp = new File::Temp( UNLINK => 1 );
    for my $user ( $adb->get_all_by_prop( type => 'ftp' ) )
    {
        my %props = $user->props;
        $props{Password} ||= '';
        $props{Chroot} ||= 'enabled';
        $props{ChrootDir} ||= '';

        next if ($props{Password} eq '');

        # generate db
        print $tmp $user->key . "\n";
        print $tmp $props{Password} . "\n";

        # create Chroot dir
        my $dir = '/var/lib/nethserver/ftp/' . $user->key;
        mkpath($dir);
        chmod 0770, $dir;
        system('/bin/chown -R ftp:ftp ' . $dir);

        if ($props{Chroot} eq 'enabled' && $props{ChrootDir} ne '' && -d $props{ChrootDir}) {
            open (USER, '>>/etc/vsftpd/users/'.$user->key);
            print USER "local_root=".$props{ChrootDir}."\n";
            close (USER);
        }
    }
    system("/usr/bin/db_load -T -t hash -f $tmp /etc/vsftpd/ftpusers.db");
    chmod 0640, "/etc/vsftpd/ftpusers.db";
}

